### ISSUE TITLE
Subgraph documentation

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-bounty-submission#1]
### Job Story

HOPR has deployed several subgraphs for applications (e.g. network analytics dashboard, staking program website, DAO voting) to consume relevant on-chain data. Despite its wide use, none of them is documented on https://docs.hoprnet.org. We look for bounty hunters to complete this void.  

_Thanks [Graph advocate Paul](https://medium.com/@paulieb.eth/subgraph-documentation-what-is-it-cfd0312ec5f5) for proactively extending their hand on this task, from which this bounty is inspired._

### Description

Currently 4 subgraphs are in use. Therefore, the scope is to document the following 4 subgraphs. Their subgraph mainnet deployments and source code are listed below.

| Name                                 | Deployment                                                                                                                           | Source code                                                                                                            |
|--------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|
| HOPR channels (`monte_rosa` release) | [Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj](https://thegraph.com/explorer/subgraphs/Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj) | [hopr-community/subgraph-channels](https://github.com/hoprnet/hopr-community/tree/main/projects/subgraph-channels)     |
| HOPR stake season 6                  | [C7cu6NvvMxgjdaK9pKSGezZ3EgRCmM4tWrmTtGUDG15t](https://thegraph.com/explorer/subgraphs/C7cu6NvvMxgjdaK9pKSGezZ3EgRCmM4tWrmTtGUDG15t) | [hopr-devrel/subgraph-stake-s6](https://github.com/hoprnet/hopr-devrel/tree/main/subgraph/packages/subgraph-stake-s6)  |
| HOPR token (mainnet)                 | [5GJcMEW1uKvE9CRddN6yg8qbPnsGuB5dg4wA1UTEQv5W](https://thegraph.com/explorer/subgraphs/5GJcMEW1uKvE9CRddN6yg8qbPnsGuB5dg4wA1UTEQv5W) | [hopr-community/subgraph-hopr-token](https://github.com/hoprnet/hopr-community/tree/main/projects/subgraph-hopr-token) |
| HOPR token (gnosis)                  | [njToE7kpetd3P9sJdYQPSq6yQjBs7w9DahQpBj6WAoD](https://thegraph.com/explorer/subgraphs/njToE7kpetd3P9sJdYQPSq6yQjBs7w9DahQpBj6WAoD)   | [hopr-devrel/hopr-on-gnosis](https://github.com/hoprnet/hopr-devrel/tree/main/subgraph/packages/hopr-on-gnosis)        |

A new section under [hoprnet/hoprnet/docs/hopr-documentation/docs/developers](https://github.com/hoprnet/hoprnet/tree/master/docs/hopr-documentation/docs/developers) should be created for subgraph docs. 

For each subgraph, 
- General description
- Contract addresses that the subgraph indexes
- Links to playground, source code, query endpoints [(Here is an example)](https://thegraph.com/explorer/subgraphs/Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj?view=Playground&chain=mainnet)
- Full documentation on entities
- Sample queries that gives some interesting info, with link to its respective sample query in GraphQL explorer.
should be included. 

There is a [good example of the subgraph documentation](https://docs.looksrare.org/developers/category/subgraph-documentation). Our community member paulieb.eth has [listed](https://medium.com/@paulieb.eth/subgraph-documentation-what-is-it-cfd0312ec5f5) their subgraph documentation work. Those examples generally reflect our expectation on the submission. 

### Definition of Done
- [ ] Create a new section "Subgraph Documentation" under "developers"
- [ ] Create subpages for each subgraph, which provides information listed in the description
- [ ] The new documentation website is successfully deployed in preview

### How to submit 

- Create a pull request to the [hoprnet repository](https://github.com/hoprnet/hoprnet) mentioning this github issue

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/dEAWC4G)

This bounty is part of [The Bounty Program](https://bounties.hoprnet.org/)

**Comment by MartinBenediktBusch** [comment]
After submission by the bounty hunter: 

I'd like both Michal and Hammad to review. 

Michal on the entity definition and query example, to see if the GraphQL example returns expected results. 

Hammad to review language (intro part) and check if the submission is consistent with the rest of docs that you (Hammad) take care of structure-wise.

**Comment by MartinBenediktBusch** [comment]
Estimated time: 8 hours 
Suggested bounty reward: 400 USD

**Comment by naftalimurgor** [comment]
Hey @MartinBenediktBusch 
I'd like to give this a shot. With focus on the following:
- concise documentation
- Relevant examples (where needed) for the subgraph

**Comment by MartinBenediktBusch** [comment]
Hi @adharasi @mjadach-iv, 

we got a submission: https://github.com/chidubemokeke/hoprnet/tree/master/docs/hopr-documentation/docs/developers/subgraph-documentation

Please review this bounty submission and get back to me with feedback.

**Comment by chidubemokeke** [comment]
Hello! I've completed the task and opened a PR https://github.com/chidubemokeke/hoprnet/tree/master/docs/hopr-documentation/docs/developers/subgraph-documentation

**Comment by mjadach-iv** [comment]
@chidubemokeke Thank you for the submission. 

Is there any particular order that you were listing the fileds in the tables? Can you please change them to always have `id` field first and then go alphabetically (a-z)?

In the [channels.md](https://github.com/chidubemokeke/hoprnet/blob/master/docs/hopr-documentation/docs/developers/subgraph-documentation/channels.md#networkregistry), you list out `Account`, `StatusSnapshot`, `Ticket`, `Channel`, `NetworkRegistry` and then in Sample Queries section you query `channels` and `statusSnapshots` both of which were not listed out in the tables before. It would be better to mention them before with information what is a difference between `account` and `accounts` and all the other similar queries. Once difference that is worth mentioning that some of them support 'where' param. The same principle applies to the rest of the md files.

In the stake-season6.md file, the `uri` should have a description: `Url to the metadate of the NFT`

**Comment by MartinBenediktBusch** [comment]
Bounty worth 400 USD got paid out
