### ISSUE TITLE
Migrate Queries to Dune SQL 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/hopr-bounty-submission#10]
### Job Story 

HOPR monitors the allocation of HOPR tokens using the following [Dashboard](https://dune.com/hopr/HOPR-Token-Allocation-Through-Distributor). In essence, the dashboard tracks the following [smart contract](https://etherscan.io/address/0xb413a589ec21cc1fec27d1175105a47628676552#readContract). In this bounty, you will migrate the Dashboard to use the Dune SQL query engine. 

### Description

Dune is changing its whole database architecture. You can read more about it [here](https://dune.com/docs/). In this bounty you will replicate each query using their new `DUNE SQL` Engine.  You can find the already decoded HOPR Distributor smart contract on Dune by selecting Dune SQL as the database, searching for hopr and selecting HoprDistributor. 

### Definition of Done

- Replicate all queries in the above mentioned Dashboard using the Dune SQL Engine
- New queries must replicate the output of the queries above (1:1). That is, no additional features should be added and no features should be deleted. However, improvements of the code are welcome. 

### How to submit 

- Create a pull request for our [hopr-bounty-submission repository](https://github.com/hoprnet/hopr-bounty-submission) 
- Submit your work into a new subfolder called ***hopr_distributor_mainnet***. 
- Submitting a link to each query is fine. 

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/dEAWC4G)

This bounty is part of [The Bounty Program](https://bounties.hoprnet.org/)

**Comment by MartinBenediktBusch** [comment]
Suggested price: 200 USD

**Comment by 0xbhagi** [comment]
I have good experience with dune SQL, and also created many dashboards in dune SQL.
https://dune.com/bhagirathnath18/
EST. Time:- 2 days

**Comment by ManyRios** [comment]
Hey! I can help with task to migrate to dune SQL! let me know if I can start work in this.

**Comment by MartinBenediktBusch** [comment]
Bounty submission merged https://github.com/hoprnet/hopr-bounty-submission/tree/main/hopr_distributor_mainnet
and paid https://etherscan.io/tx/0x4b7b405588529491217fe2339c200c6cb7aaee2289d88005f1993c1a843a7fdd
