### ISSUE TITLE
Subgraph Documentation (staking seasons) 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/hopr-bounty-submission#2]
### Job Story

HOPR has deployed several subgraphs for applications (e.g. network analytics dashboard, staking program website, DAO voting) to consume relevant on-chain data. We are looking for bounty hunters to write the documentation.   

### Description

The scope of this bounty is to document the following subgraph (subgraph deployment and source code are listed below)

| Name                                 | Deployment                                                                                                                           | Source code                                                                                                            |
|--------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|
| Subgraph all staking seasons        | [DrkbaCvNGVcNH1RghepLRy6NSHFi8Dmwp4T2LN3LqcjY](https://thegraph.com/explorer/subgraphs/DrkbaCvNGVcNH1RghepLRy6NSHFi8Dmwp4T2LN3LqcjY) | [hopr-devrel/subgraph-all-seasons](https://github.com/hoprnet/hopr-devrel/tree/main/subgraph/packages/subgraph-all-seasons)  | 

The subgraph documentation should contain, 
- General description
- Contract addresses that the subgraph indexes
- Links to playground, source code, query endpoints [(Here is an example)](https://thegraph.com/explorer/subgraphs/Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj?view=Playground&chain=mainnet)
- Full documentation on entities
- Sample queries that gives some interesting info, with link to its respective sample query in GraphQL explorer.
should be included. 

There is a [good example of the subgraph documentation](https://docs.looksrare.org/developers/category/subgraph-documentation). Our community member paulieb.eth has [listed](https://medium.com/@paulieb.eth/subgraph-documentation-what-is-it-cfd0312ec5f5) their subgraph documentation work. Those examples generally reflect our expectation on the submission. 

Description of each entity/property can be found in [the smart contract documentation](https://docs.hoprnet.org/developers/smart-contract) or in the code comments [next to the source code](https://github.com/hoprnet/hoprnet/tree/master/packages/ethereum/contracts/src)

### Definition of Done
- [ ] Migrate/rebase the [PR#4564](https://github.com/hoprnet/hoprnet/pull/4564) into the new repo (hoprnet/hopr-docs).
- [ ] Extend the section "Subgraph Documentation" for the "subgraph-all-seasons"
- [ ] Provide more details in the description of each entity/property for all the subgraphs.
- [ ] The new documentation website is successfully deployed in preview

### How to submit 

- Create a pull request to the [hopr-docs repository](https://github.com/hoprnet/hopr-docs) mentioning this github issue

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/dEAWC4G)

This bounty is part of [The Bounty Program](https://bounties.hoprnet.org/)

**Comment by MartinBenediktBusch** [comment]
Hi @QYuQianchen, 

please review this issue. In particular, 

- include the name deployment and source code for the all staking seasons subgraph that should be documented. 
- check whether the following is still correct for the subgraph. Otherwise change it: A new section under [hoprnet/hoprnet/docs/hopr-documentation/docs/developers](https://github.com/hoprnet/hoprnet/tree/master/docs/hopr-documentation/docs/developers) should be created for subgraph docs.
- replace the example refering to a "good subgraph documentation" with the submission of the most recent subgraph documentation in order for our documentation to stay consistent. 
-  Check the definition of Done section

**Comment by MartinBenediktBusch** [comment]
Estimated Time: 4 hours 
Estimated Reward: 200 USD paid in HOPR token

**Comment by chidubemokeke** [comment]
@MartinBenediktBusch I migrated PR #4564 to [hopr-docs repository](https://github.com/hoprnet/hopr-docs),  added the new documentation for the staking-seasons subgraph and opened a new PR #18.
Kindly review.

**Comment by MartinBenediktBusch** [comment]
Paid amount 200 USD: https://etherscan.io/tx/0x0d43714357aec9fe48e521cad821b178bafb1cca276e0eeb5e7cd1ccb1d2bf24
