### ISSUE TITLE
RPCh prototype project and documentation review

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-bounty-submission#3]
### Job Story

RPCh has recently introduced developer [docs](https://docs.rpch.net) so devs can integrate RPCh into their projects.
This bounty, wants you to create a prototype that uses the RPCh network and review the [docs](https://docs.rpch.net).

### Description

- Read the [docs](https://docs.rpch.net) and create a prototype project which uses the [RPCh SDK](https://docs.rpch.net/docs/guides/using-the-sdk) or [RPCh ethers](https://docs.rpch.net/docs/guides/using-ethers). The prototype should be able to send at least 1 transaction through the RPCh network. Note that you must have Node.js and npm/yarn installed on your computer to complete this bounty. You can download them from their official website or use a package manager like Homebrew (for Mac) or Chocolatey (for Windows).
- Once you have completed the prototype, we would like you to provide feedback on the docs.

### Submission Deadline

`26/04/2023`

### Definition of Done

- link to the prototype's repository. We will verify whether the prototype is able to send at least 1 transaction through the RPCh network.
- Rate the docs from 1 to 10, 1 being very difficult to understand, 10 being very easy.

Give us specific feedback on the following questions:
- what was the most diffictult part to understand in the RPCh docs in relation to this task?
- what would you improve in the docs?
- what was your overall experience (please describe)?

### How to submit 

- Create a pull request for our [hopr-bounty-submission repository](https://github.com/hoprnet/hopr-bounty-submission). 
- Submit your work into a new subfolder called ***RPCh documentation review (your github username)***.

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/dEAWC4G)

This bounty is part of [The Bounty Program](https://bounties.hoprnet.org/)

**Comment by 0xbhagi** [comment]
Gitcoin start button is giving error, I want to work on this bounty as per  given instruction .

**Comment by MartinBenediktBusch** [comment]
Replied to you on Discord :)

**Comment by web3files** [comment]
initial coding part just done . trying to execute the transaction.

**Comment by web3files** [comment]
![RPCH](https://user-images.githubusercontent.com/97182070/234305788-a83f5506-e8c8-45aa-9aaf-919aa56f1c66.PNG)
it shows error when trying to connect to the "gnosis on RPCh" network

**Comment by web3files** [comment]
I have read the docs , giving 8 out of 10 . The documentation is understandable but can't connect the wallet to the Gnosis on RPCh network (it shows the network is down). Submitted the prototype . Looking forward for any questions and bounty.

**Comment by web3files** [comment]
Make sure Gnosis on RPCh network is running properly . That's the main issue.

**Comment by MartinBenediktBusch** [comment]
Hi @web3files could you give us feedback on the following questions to complete the bounty?

what was the most diffictult part to understand in the RPCh docs in relation to this task?
what would you improve in the docs?
what was your overall experience (please describe)?

**Comment by web3files** [comment]
Here is the answer regarding these questions (

What was the most difficult part to understand in the RPCh docs in relation to this task?

What would you improve in the docs?

)

Ans: 

1.  most difficult part to understand(according this docs part [https://docs.rpch.net/docs/guides/using-the-sdk](https://docs.rpch.net/docs/guides/using-the-sdk)):
    
    The most difficult part to understand for creating a prototype that should be able to send at least one transaction through the RPCh network is likely the understanding of the RPCh SDK's inner workings and the associated cryptographic operations required to securely interact with the network. The process involves installing the necessary packages, creating an instance of the SDK with required options and key-value store functions, starting the SDK, creating and sending requests through the network, and stopping the SDK after use. Additionally, understanding how to enable debugging logs is important to ensure effective troubleshooting of issues that may arise. A solid understanding of the SDK's documentation and example integrations can help in creating a functional prototype.
    

      

Here are some suggestions for improving this to enhance its clarity and understanding:

1.  Add a brief introduction: Consider adding a brief introduction to explain what the RPCh SDK is and why it's important.
2. Simplify the language: While it's important to be accurate and precise, try to use simpler language where possible to make the content more accessible to a wider audience.
3. Use subheadings: Break up the content into smaller sections with subheadings to make it easier to scan and understand.
4. Add examples: Provide concrete examples of how to use the SDK to make it easier for developers to understand.
5. Include visuals: Visual aids like diagrams or screenshots can help readers better understand complex processes.
6. Provide more context: Provide more context about the HOPR network and how the SDK fits into it to help readers better understand the importance of the SDK.
7. Discuss future developments: Mention any future developments or updates to the SDK and how they will improve its functionality.

1. most difficult part to understand (according to this docs part [https://docs.rpch.net/docs/guides/using-ethers](https://docs.rpch.net/docs/guides/using-ethers)):
    1. this documentation is likely to be the configuration and initialization of the RPChProvider instance. This involves passing in multiple options, including the URL of the provider, the RPCh SDK options, and key-value store functions. Additionally, understanding how to use the send method to send requests to the provider can also be a bit challenging.
    
    Here are some suggestions for improving this to enhance its clarity and understanding:
    
    1. Provide more context: Before diving into the configuration and initialization of the RPChProvider instance, it would be helpful to provide some background information on what the RPCh network is, why it's useful, and how it works.
    2. Break down the initialization process: Instead of providing a large block of code for the initialization process, consider breaking it down into smaller, more manageable steps. Provide clear explanations for each step and what it does, and include code snippets that show how to implement each step.
    3. Provide more examples: While the example integration with BlockWallet is helpful, providing additional examples of how to use RPCh ethers adaptor in different contexts would be beneficial. This could include examples for different wallets, exchanges, or other applications that interact with the Ethereum network.
    4. Use simpler language: The current documentation can be a bit technical and difficult to understand for those who are new to the RPCh network or Ethereum development in general. Consider using simpler language and providing explanations for technical terms and concepts.
    5. Include troubleshooting tips: If users encounter any issues during the implementation process, it would be helpful to include troubleshooting tips or a FAQ section that addresses common problems and their solutions.
2. most difficult part to understand (according to this docs part [https://docs.rpch.net/docs/tutorial-basics/What-is-RPCh](https://docs.rpch.net/docs/tutorial-basics/What-is-RPCh)):
    1. this documentation is likely to be the technical details surrounding the implementation of the HOPR mixnet and how it is utilized by the RPCh service.
    
    Here are some suggestions for improving this to enhance its clarity and understanding:
    
    1. Provide a clear overview of the HOPR mixnet and its components: Start with an introductory section that provides a high-level overview of what the HOPR mixnet is and how it works. This should include an explanation of the different components of the mixnet, such as the relays, nodes, and protocols.
    2. Explain the role of RPCh in the mixnet: Provide a detailed description of how the RPCh service fits into the HOPR mixnet architecture. This should include information on how the RPCh service communicates with the mixnet and how it uses the mixnet's privacy-preserving features to protect user data.
    3. Include technical details on the implementation: Provide in-depth technical details on how the HOPR mixnet and RPCh service are implemented. This should include information on the programming languages, frameworks, and libraries used in the implementation, as well as a detailed description of the system architecture.
    4. Provide examples and use cases: To help users better understand how the HOPR mixnet and RPCh service can be used, provide real-world examples and use cases. This could include scenarios where the privacy-preserving features of the mixnet are particularly useful, such as when working with sensitive financial data.
    5. Include a troubleshooting section: Finally, include a troubleshooting section that addresses common issues that users may encounter when working with the HOPR mixnet and RPCh service. This should include tips on how to troubleshoot issues and where to go for additional support if needed.

At last here is the answer regarding your question (what was your overall experience (please describe)?)

The documentation does provide a good introduction to the problem of data leaks in crypto wallets and the solution that RPCh provides. It also includes an overview of the RPCh design and links to additional resources for further reading.

The documentation can be very useful in understanding the implementation details of RPCh and the HOPR mixnet, as well as how to utilize them to improve privacy for blockchain applications. However, some of the technical details and concepts may be challenging for developers who are not familiar with the specific technologies and protocols involved.

To improve the documentation for better understanding, it may be helpful to provide more examples and practical use cases of how to implement RPCh and the HOPR mixnet in real-world scenarios. Additionally, breaking down complex technical concepts into simpler language and providing step-by-step instructions can also be useful for developers who are new to the technologies. Also provide some more diagrams .

**Comment by web3files** [comment]
Feel free to ask any question .

**Comment by web3files** [comment]
Hi any updates? What happened?

**Comment by MartinBenediktBusch** [comment]
Hi, 

sorry for the late reply. I can give you an update tomorrow :)

**Comment by web3files** [comment]
Okay

**Comment by web3files** [comment]
Subject: Payment for my submitted work

Dear HOPRNET team,

I hope this message finds you well. I wanted to follow up on the payment for my submitted work, as I understand that your blockchain ecosystem is currently down. I greatly appreciate the opportunity to contribute to your project and I am looking forward to receiving payment as soon as possible.

Given the current situation, I would like to request to receive payment in **ETH** via this address **0xb75D481F3b1d0d98510831efE03F5A61D32f085b** on **Ethereum** ecosystem instead of your project's tokens (**HOPR**)  . I believe this would be a more practical option at this time.

Please let me know if there are any other details I should be aware of. Thank you for your attention to this matter.

Best regards,
web3files

**Comment by MartinBenediktBusch** [comment]
Hi @web3files,

we are very happy with your submission and will pay you as promised :) We will pay you 200 USD in HOPR over Gitcoin as stated in the bounty. We will pay out the bounty to you on Monday.

**Comment by web3files** [comment]
okay

**Comment by MartinBenediktBusch** [comment]
Bounties have been paid out to web3files and 0xbhagi

**Comment by web3files** [comment]
At which address did you pay the bounty ? I haven't received it yet .
![Capture](https://user-images.githubusercontent.com/97182070/236860159-616420c6-d33e-4e7b-8368-dc91f88af604.PNG)

**Comment by MartinBenediktBusch** [comment]
Its HOPR on Mainnet: 
https://etherscan.io/tx/0xc0bb48f56054967b3ae0a5b8e645dfe7de021bedd5a292870b2e2c6196a47134

to see it switch the netwrok to Ethereum Mainnet. If zou cannot see the token click import token and insert the following token address: 0xF5581dFeFD8Fb0e4aeC526bE659CFaB1f8c781dA

Let me know if this solved the issue.

**Comment by web3files** [comment]
Got it .Thank you so much .
