### ISSUE TITLE
Improve RPCh integration in the Argent X fork

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-bounty-submission#9]
### Description

Continue the work on the [argent-x extension](https://github.com/Rpc-h/extension-argent-x).
The objective of this follow-up bounty is to polish up the existing snap and make it more production ready.

Currently, RPCh does not _fully_ support Starknet requests, one of the limitations is that we cannot `read` request responses.
However, RPCh plans to introduce Starknet support - so while that is not ready, you may use a server which mocks Starknet's responses to enable you to continue the integration.

### Definition of Done

- remove all newly added debug logs that are not needed
- revert `build` script in `package.json` to its original
- add support for `mainnet-alpha` network
- use long-term storage rather than `createAsyncKeyValStore`
- support for reading responses

### How to Apply 

- Submit a work plan in your application on Gitcoin 
- Provide an estimate of how much time you think you need to complete the bounty

### How to submit 

- Create a pull request for our [hopr-bounty-submission repository](https://github.com/hoprnet/hopr-bounty-submission) 
- Submit your work into a new subfolder called ***"Improve_rpch_integration_argent_X***.

### What is RPCh?

Find out more about RPCh at the following links:

- [RPCh Website](https://rpch.net)
- [RPCh monorepo](https://github.com/rpc-h/rpch)
- [RPCh docs](https://docs.rpch.net)
- [discord](https://discord.com/invite/dEAWC4G)

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/7RqwJt8h)

This bounty is part of [The Bounty Program](https://bounties.hoprnet.org/)

**Comment by ManyRios** [comment]
Hey @nionis I'm ready to help with this!

**Comment by nionis** [comment]
hey @smilephoenix103 any progress update?

**Comment by smilephoenix103** [comment]
I am working on it.
Last 10 days, I was in hospital for stomach bleeding.
Now I am recovered, and I can work.
I will update soon.

Sorry for delaying our work.

**Comment by web3files** [comment]
@MartinBenediktBusch Hi I want to work for this bounty .

**Comment by web3files** [comment]
I can deliver it pretty soon

**Comment by nionis** [comment]
hey @smilephoenix103, any updates?

**Comment by web3files** [comment]
@nionis HI I want to work for this bounty . I am really interested

**Comment by web3files** [comment]
I would love to complete the following steps to get this job done :

Step 1: Familiarize myself with Existing Codebase

Clone the "argent-x" repository from Gitcoin.
Review the current implementation and understand its structure.
Identify the areas that require improvement according to the bounty description.

Step 2: Set Up Development Environment

Install the necessary dependencies for development.
Configure the project to work with my local development environment.
Ensure that all required tools and libraries are properly installed.

Step 3: Remove Unnecessary Debug Logs

Identify any debug logs that were added recently and are no longer needed.
Go through the codebase and remove these debug logs.
Ensure that the removal of logs does not affect the functionality of the extension.

Step 4: Revert Build Script in package.json

Locate the modified build script in the package.json file.
Revert the build script to its original state.
Test the build process to confirm that it is working as expected.

Step 5: Add Support for mainnet-alpha Network

Update the extension to include support for the mainnet-alpha network.
Modify the necessary configuration files to enable connectivity to the mainnet-alpha network.
Test the integration with the mainnet-alpha network to ensure its functionality.

Step 6: Implement Long-Term Storage

Replace the usage of createAsyncKeyValStore with a long-term storage solution.
Evaluate different storage options (e.g., local storage, IPFS) and choose the most suitable one for the extension.
Integrate the chosen long-term storage solution into the codebase.
Verify that the extension works correctly with the new storage implementation.

Step 7: Support Reading Responses

Update RPCh to support reading responses from Starknet.
Utilize a server that mocks Starknet's responses to enable response reading until RPCh fully supports Starknet requests.
Integrate the mocked response functionality into the extension.
Test the extension to ensure that reading responses from Starknet works as intended.

Step 8: Code Review and Testing

Conduct a thorough code review to identify any potential issues or areas for improvement.
Address any code review feedback and make the necessary modifications.
Test the extension under different scenarios and networks to verify its stability and reliability.

Step 9: Documentation and Submission

Document any changes or improvements made to the codebase.
Create a pull request for the "hopr-bounty-submission" repository.
Submit my work into a new subfolder named "Improve_rpch_integration_argent_X."
Provide a detailed description of the implemented changes and improvements.

Step 10: Respond to Feedback

Address any feedback or comments provided by the project maintainers.
Make any necessary adjustments or fixes based on the feedback received.
Collaborate with the project maintainers to ensure the successful integration of my work.

**Comment by ManyRios** [comment]
Hey @nionis I'm able to help with this task

**Comment by smilephoenix103** [comment]
Hi, @nionis 
Surely, I updated already, 
But, I have no write access.
Could you please give me permission to push and create pull request? :)

**Comment by nionis** [comment]
@smilephoenix103 please create a fork and push there

**Comment by nionis** [comment]
@MartinBenediktBusch since @smilephoenix103 has not replied neither here or direct messages, can we assign this to a new person?

**Comment by smilephoenix103** [comment]
Hi, @nionis , @MartinBenediktBusch 
I updated a lot and push soon.
everything will be completed soon.

I am so sorry to late reply,
I have got my health problem.
I have got my health problem about not fully recovered my last stomach blooding emergency problem.

Could you please forgive with a generous and open mined?
I will dedicated all of mine to you, 
I will finish all till this weekend.

Thank you a lot and sorry really sorry.




> @MartinBenediktBusch since @smilephoenix103 has not replied neither here or direct messages, can we assign this to a new person?

**Comment by ManyRios** [comment]
I'm able to help @nionis and @MartinBenediktBusch if you're going to  re-assign
